// Lista de Cargos (Job Titles)
export const jobTitles = [
  'Administrador de Datos BIM',
  'Arquitecto',
  'Cliente/Propietario',
  'Consultor de Sustentabilidad',
  'Coordinador BIM',
  'Encargado de Seguridad',
  'Ingeniero Civil',
  'Ingeniero de Costos/Quantity Surveyor',
  'Ingeniero Estructural',
  'Ingeniero MEP',
  'Mantenimiento/Operador',
  'Manager BIM',
  'Supervisor de Control de Calidad',
  'Topógrafo',
  'Project Manager',
  'Supervisor General',
  'Otro',
];
  
  // Lista de Países (Countries)
  export const countries = [
    'Alemania',
    'Argentina',
    'Brasil',
    'Canadá',
    'Chile',
    'Colombia',
    'Dinamarca',
    'Ecuador',
    'España',
    'Estados Unidos',
    'Francia',
    'Italia',
    'México',
    'Noruega',
    'Países Bajos',
    'Paraguay',
    'Perú',
    'Reino Unido',
    'Suecia',
    'Suiza',
    'Uruguay',
    'Venezuela',
    'Otro',
  ];