// Lista de Cargos (Job Titles)
export const jobTitles = [
    'Architect',
    'Civil Engineer',
    'Structural Engineer',
    'MEP Engineer',
    'General Contractor',
    'BIM Manager',
    'BIM Coordinator',
    'Project Manager',
    'Quality Control Technician',
    'Surveyor',
    'Geomensor',
    'Sustainability Consultant',
    'Safety Specialist',
    'BIM Data Administrator',
    'Operator/Maintenance',
    'Client/Owner',
    'Cost Engineer/Quantity Surveyor',
    'Other',
  ];
  
  // Lista de Países (Countries)
  export const countries = [
    'United States',
    'Canada',
    'United Kingdom',
    'Australia',
    'Germany',
    'France',
    'Brazil',
    'India',
    'China',
    'Japan',
    'Mexico',
    'South Africa',
    'Argentina',
    'Chile',
    'Colombia',
    'Spain',
    'Italy',
    'Netherlands',
    'Sweden',
    'Norway',
    'Finland',
    'Denmark',
    'Switzerland',
    'New Zealand',
    'Singapore',
    'South Korea',
    'Other',
  ];